### ISSUE TITLE
Unable to rename group

### ISSUE THREAD

**Issue by xaque208** [amimof/huego#16]
I get the following error when trying to call `group.Rename()`: ERROR 6 [/groups/9/state]: "parameter, state, not available"

Is this a change in the API perhaps?  Using the version of this code.

**Comment by xaque208** [comment]
Renaming a light works fine.

**Comment by amimof** [comment]
@xaque208 Thanks for reporting. According to the official Philips Hue API documentation, only `name`, `lights` and `class` may be updated on an existing group. All other fields seems to immutable. I'll try to have this fixed during this week. You are welcome to submit a PR if you like.
