### ISSUE TITLE
Proposal: Please start using Semantic Versioning

### ISSUE THREAD

**Issue by KateGo520** [amimof/huego#23]
I found that this project already [supports Go modules](https://github.com/amimof/huego/blob/master/go.mod). But sadly, the [tags](https://github.com/amimof/huego/tags) doesn't follow [Semantic Versioning](https://semver.org), which means that all tags of this project will be ignored by Go modules and replaced by pseudo-versions, go get acts weirdly when tags are not in that form. It would be great to have the tagged release be named in the format vX.X.X format so that go mod can read it. 
```
	github.com/amimof/huego v0.0.0-20200504200310-b4a8f71aa2e3
```
Else the mod file shows something like `github.com/amimof/huego v0.0.0-20200504200310-b4a8f71aa2e3` which is not very readable and difficult to upgrade. It’s hard to verify which version is in use. This is not conducive to version control

So, I propose this project to follow Semantic Versioning in future versions. For example, `v1.0.1`, `v2.0.0`, `v3.1.0-alpha`, `v3.1.0-beta.2`etc.

**Comment by KateGo520** [comment]
@amimof  @smonesi  Could you help me review this issue? Thx :p

**Comment by amimof** [comment]
@KateGo520 Thanks for reporting. I would assume this is because the tags are missing the `v` prefix. We could simply just add those tags so that the commits have two.

**Comment by KateGo520** [comment]
Thank you for your reply! @amimof  
That would be great, if the version tag `1.1.0` turn to `v1.1.0`  .

**Comment by amimof** [comment]
@KateGo520 See https://github.com/amimof/huego/releases/tag/v1.1.0

**Comment by KateGo520** [comment]
@amimof  I see the new tag! Thank you for your contribution!

**Comment by amimof** [comment]
@KateGo520 Thank you! 👏
