### ISSUE TITLE
Won't "login"

### ISSUE THREAD

**Issue by strotyl** [amimof/huego#33]
I'm able to use the "discover -> create user" when I press the button on the bridge, but I'm not able to get the "new" command to work. Each time I run the line it says "ERROR 1 [/lights]: "unauthorized user"

But I know I've created that user ( by pushing the button and running the other code ) many times! Help.

`bridge := huego.New("192.168.1.4", "tyler")`

**Comment by amimof** [comment]
Hi @strotyl 
Just wanted to check in to hear if the issue is resolved since you closed it :)

**Comment by strotyl** [comment]
Wow! Thanks for follow up.I did! After some investigation ( looking at the actual HTTP requests being send) I discovered the "username" being sent in the URL by the "New()" command is very different than the username being sent in the URL by the Discover/CreateUser workflow. For example... The user I created was "Tyler" but I wasn't able to login as that. When I created the "Tyler" user and looked at the posts the user being sent was something like... "WxIildj2UqBQ0...". I started using that name in my New() calls and it did work. 

I don't assume this is correct but I didn't want to bother you with it since I got it working. :)

**Comment by amimof** [comment]
I believe with Discover/CreateUser the bridge generates the key, which Philips calls `username`. So when you use the `New()` function, which instantiates a new instance of Huego it assumes the `username` which in your case is `WxIildj2UqBQ0...`. Hope it makes sense :)
