### ISSUE TITLE
tags format for Go modules

### ISSUE THREAD

**Issue by pierrre** [amimof/huego#36]
Hello,

According to https://golang.org/ref/mod the Git tag format should be `vX.Y.Z`.
So the tag for the version 1.2.0 should be `v1.2.0` instead of `1.2.0`.
Currently the versions are not displayed here https://pkg.go.dev/github.com/amimof/huego?tab=versions
and all the links to the source code are broken https://pkg.go.dev/github.com/amimof/huego
(pkg.go.dev is replacing godoc.org)

**Comment by amimof** [comment]
Hi @pierrre Thanks for reporting. I'll make sure to have the tag names fixed asap.

**Comment by amimof** [comment]
I just added tags with `v` prefix

**Comment by pierrre** [comment]
great, it's working !
https://pkg.go.dev/github.com/amimof/huego?tab=versions
