### ISSUE TITLE
Feature Request: Utility methods: Convert HEX Color to xy and back

### ISSUE THREAD

**Issue by willie68** [amimof/huego#37]
Hi,
on some other SDKs (mainly directly from philips/Signify) there are some utility methods to convert RGB colors into XY.
It would be nice, if you can add this to your lib. Some background informations:
https://developers.meethue.com/develop/application-design-guidance/color-conversion-formulas-rgb-to-xy-and-back/

**Comment by willie68** [comment]
And another question:
Why is huego looking so bored? :-)

**Comment by amimof** [comment]
@willie68 Makes sense, thanks for the input. He's bored because there are no light switches to press :)

**Comment by amimof** [comment]
Fixed in #39
