### ISSUE TITLE
CreateUser

### ISSUE THREAD

**Issue by JulianSauer** [amimof/huego#6]
Running the example from the readme I get an error:

```
func main() {
  bridge, _ := huego.Discover()
  user, _ := bridge.CreateUser("my awesome hue app") // Link button needs to be pressed
  bridge = bridge.Login(user)
  light, _ := bridge.GetLight(3)
  light.Off()
}
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x60ab3b]

goroutine 1 [running]:
github.com/amimof/huego.(*Bridge).getAPIPath(0x0, 0xc042089d60, 0x3, 0x3, 0x40, 0x0, 0x0, 0x62a740)
        C:/Go/bin/src/github.com/amimof/huego/bridge.go:21 +0x4b
github.com/amimof/huego.(*Bridge).SetLightState(0x0, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        C:/Go/bin/src/github.com/amimof/huego/bridge.go:487 +0x181
github.com/amimof/huego.(*Light).Off(0xc0421da0a0, 0x3, 0xc0421da0a0)
        C:/Go/bin/src/github.com/amimof/huego/light.go:59 +0xa7
main.main()
        C:/Users/Julian/Documents/WaterCan/main/main.go:16 +0x126
exit status 2
```

**Comment by amimof** [comment]
The example don't handle errors for sake of readability. My guess is that your bridge doesn't know any light by id of 3. Try to handle the errors to try pinpoint what is going on.

**Comment by JulianSauer** [comment]
CreateUser throws an error: `ERROR 101 []: "link button not pressed"`
When exactly do I need to press the link button? I would have expected the program to wait for it to be pressed when I try to create a user.

**Comment by amimof** [comment]
You need to press the link button before in order to authorise user creation on the bridge. However I do like the idea to include a helper function that could wait until button is pressed for let's say 60s. Maybe I will add it in a future version. You are of course welcome to open a pull request and contribute to the project.

**Comment by JulianSauer** [comment]
Ah that works, thanks for the quick reply!
