### ISSUE TITLE
Add context.Context support in APIs

### ISSUE THREAD

**Issue by ereOn** [amimof/huego#8]
First, thanks for this library: the work is outstanding and I really, really love it! Impressive work!

I am integrating Huego (and many other libraries) into a library for my home-automation hub. My goal is to provide a technology-agnostic REST web-service.

A very common pattern for web-services, is to handle properly requests lifetime by honoring the status of the `context.Context` that is attached to `*http.Request` instances. Since this context automatically expires when the client underlying connection closes (or any other fatal network condition), this allows for circuit-breaking: for instance, if I use the `context.Context` from the HTTP request and pass it in an underlying "turn this light on" operation, and the initiating request closes early, it gives a chance to the program to avoid doing unnecessary work by also stopping the "turn this light on" operation sooner.

It is as simple as doing:

```
req = req.WithContext(ctx)
```

Before issuing a HTTP request.

The current Huego APIs don't expose a way of passing in a `context.Context` for each operation. Is that something you'd be interested in? I can probably make a pull-request for it, but I figured I'd discuss it with you first.

There is a way to do that without breaking the API by "overloading" each operation method with a `Ctx` suffix. Say:

```
// Context creation: can be done in many ways.
ctx, cancel := context.WithTimeout(context.Background(), time.Second)
defer cancel()

// Example call.
light.OnCtx(ctx) // Guaranteed to complete when the operation is over or one second passes by, whichever happens first.
```

Please let me know what you think of this.

**Comment by amimof** [comment]
Hi, thank you for your input, kind words and interest in the project 👏 

Awesome feedback and i totally agree that it should be possible to pass  in a `context.Context`. I feel that it could be possible to do so in a constructor instead. For example 

Adding `ctx` to `Bridge` struct in `bridge.go`
```golang 
type Bridge struct {
	Host string `json:"internalipaddress,omitempty"`
	User string
	ID   string `json:"id,omitempty"`
	ctx  context.Context  // <-- add this
}
```

Add new initialiser method `NewWithContext()` in `huego.go`:
```golang
func NewWithContext(h, u string, c context.Context) *Bridge {
	return &Bridge{h, u, "", c}
}
```

and update current `New()` method in `huego.go`
```golang
func New(h, u string) *Bridge {
	return NewWithContext(h, u, context.Background())
}
```

What do you think?

**Comment by ereOn** [comment]
@amimof I'm not sure it would be the right pattern for the case I mentionned: a `context.Context` is usually short-lived (the lifetime of an incoming request).

While that solution would imply minimal changes in the library, it would force the user to instanciate a new `Bridge` for every request, and prevent concurrent usage of the same `Bridge` instance with different contexts. Also, it forces users to have the context at the Bridge initialization time instead of at the usage time, which somehow doesn't feel right to me.

Let me know if that makes sense.

**Comment by amimof** [comment]
@ereOn Yeah you are right, didn't think about that. I really want to avoid adding all those additional methods for each operation, but can't think of another way. How about this

Modify `get()`, `put()`, `post()` and `delete()` in `main.go` to accept a `ctx` argument, for example:
```golang
func get(ctx context.Context, url string) ([]byte, error) {
...
}}
```

Add additional methods for each operation like this:
```golang
func (b *Bridge) GetCapabilities() (*Capabilities, error) {
	return b.GetCapabilitiesCtx(nil)
}

func (b *Bridge) GetCapabilitiesCtx(ctx context.Context) (*Capabilities, error) {
	s := &Capabilities{}

	url, err := b.getAPIPath("/capabilities/")
	if err != nil {
		return nil, err
	}

	res, err := get2(ctx, url)
	if err != nil {
		return nil, err
	}

	err = unmarshal(res, &s)
	if err != nil {
		return nil, err
	}

	return s, err
}
```

**Comment by kkirsche** [comment]
I think this is a good approach, I just wanted to add a blog post about contexts for those who read this who may not be as familiar with why Contexts are used

https://blog.golang.org/context

**Comment by amimof** [comment]
Just came back from a long parental leave. But I'll try to get something to start with as soon as I can.
